baseurl: "/"
languageCode: "en-us"
title: "Shouqiang Wang"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  research: "/research/:year/:month/:day/:slug/"
  teaching: "/teaching/:year/:month/:day/:slug/"
  others: "/others/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Research
      url: "research/"
      weight: 2
    - name: Teaching
      url: "teaching/"
      weight: 3
    - name: Others
      url: "others/"
      weight: 4

params:
  description: "Shouqiang Wang homepage."
  footer: "&copy; Shouqiang Wang 2021 -- 2021 | [Google Scholar](https://scholar.google.com/citations?user=vYRqio4AAAAJ&hl=en) "

markup:
  goldmark:
    renderer:
      unsafe: true
